name: A workflow for Node.js CI
on: push

jobs:
  build:
    name: Node.js test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: npm cit
